struct vex2d;
struct vex2i;
struct vex2f;
struct vex3d;
struct vex3i;
struct vex4d;
struct vex4i;
struct vex4f;
struct vex3f {
	float x, y, z;
	vex3f();
	vex3f(float v1, float v2, float v3);
	vex3f(float v1, float v2);
	vex3f(float v1);
	vex3f(bool& v1, bool& v2, bool& v3) { x = std::atof(v1); y = std::atof(v2); z = std::atof(v3); };
	vex3f(bool& v1, bool& v2) { x = std::atof(v1); y = std::atof(v2); };
	vex3f(bool& v1) { x = std::atof(v1); y = std::atof(v1); z = std::atof(v1); };
	vex3f(std::string v1, std::string v2, std::string v3) { x = std::atof(v1.c_str()); y = std::atof(v2.c_str()); z = std::atof(v3.c_str()); };
	vex3f(std::string v1, std::string v2) { x = std::atof(v1.c_str()); y = std::atof(v2.c_str()); };
	vex3f(std::string v1) { x = std::atof(v1.c_str()); y = std::atof(v1.c_str()); z = std::atof(v1.c_str()); };
	vex3f(vex2d v);
	vex3f(vex2i v);
	vex3f(vex2f v);
	vex3f(vex3d v);
	vex3f(vex3i v);
	vex3f(vex4f v);
	vex3f(vex4d v);
	vex3f(vex4i v);

	vex3f(vex2f v, float v1);
	vex3f(float v1, vex2f v);
	vex3f(vex2d v, float v1);
	vex3f(float v1, vex2d v);
	vex3f(vex2i v, float v1);
	vex3f(float v1, vex2i v);
	   
	vex3f(vex2f v, double v1);
	vex3f(double v1, vex2f v);
	vex3f(vex2d v, double v1);
	vex3f(double v1, vex2d v);
	vex3f(vex2i v, double v1);
	vex3f(double v1, vex2i v);
	   
	vex3f(vex2f v, int v1);
	vex3f(int v1, vex2f v);
	vex3f(vex2d v, int v1);
	vex3f(int v1, vex2d v);
	vex3f(vex2i v, int v1);
	vex3f(int v1, vex2i v);

	void operator= (vex2d v);
	void operator= (vex2i v);
	void operator= (vex2f v);
	void operator= (vex3d v);
	void operator= (vex3i v);
	void operator= (vex4f v);
	void operator= (vex4d v);
	void operator= (vex4i v);

	vex3f operator+ (vex4f v);
	vex3f operator- (vex4f v);
	vex3f operator* (vex4f v);
	vex3f operator/ (vex4f v);
	vex3f operator+ (vex4d v);
	vex3f operator- (vex4d v);
	vex3f operator* (vex4d v);
	vex3f operator/ (vex4d v);
	vex3f operator+ (vex4i v);
	vex3f operator- (vex4i v);
	vex3f operator* (vex4i v);
	vex3f operator/ (vex4i v);
	vex3f operator+ (vex3i v);
	vex3f operator- (vex3i v);
	vex3f operator* (vex3i v);
	vex3f operator/ (vex3i v);
	vex3f operator+ (vex3d v);
	vex3f operator- (vex3d v);
	vex3f operator* (vex3d v);
	vex3f operator/ (vex3d v);
	vex3f operator+ (vex2f v);
	vex3f operator- (vex2f v);
	vex3f operator* (vex2f v);
	vex3f operator/ (vex2f v);
	vex3f operator+ (vex2i v);
	vex3f operator- (vex2i v);
	vex3f operator* (vex2i v);
	vex3f operator/ (vex2i v);
	vex3f operator+ (vex2d v);
	vex3f operator- (vex2d v);
	vex3f operator* (vex2d v);
	vex3f operator/ (vex2d v);
	vex3f operator+ (vex3f v);
	vex3f operator- (vex3f v);
	vex3f operator* (vex3f v);
	vex3f operator/ (vex3f v);

	vex3f operator+ (float v);
	vex3f operator- (float v);
	vex3f operator* (float v);
	vex3f operator/ (float v);
	void operator= (float v);

	void operator+= (vex4d v);
	void operator-= (vex4d v);
	void operator*= (vex4d v);
	void operator/= (vex4d v);
	void operator+= (vex4i v);
	void operator-= (vex4i v);
	void operator*= (vex4i v);
	void operator/= (vex4i v);
	void operator+= (vex4f v);
	void operator-= (vex4f v);
	void operator*= (vex4f v);
	void operator/= (vex4f v);
	void operator+= (vex3i v);
	void operator-= (vex3i v);
	void operator*= (vex3i v);
	void operator/= (vex3i v);
	void operator+= (vex3d v);
	void operator-= (vex3d v);
	void operator*= (vex3d v);
	void operator/= (vex3d v);
	void operator+= (vex2f v);
	void operator-= (vex2f v);
	void operator*= (vex2f v);
	void operator/= (vex2f v);
	void operator+= (vex2i v);
	void operator-= (vex2i v);
	void operator*= (vex2i v);
	void operator/= (vex2i v);
	void operator+= (vex2d v);
	void operator-= (vex2d v);
	void operator*= (vex2d v);
	void operator/= (vex2d v);

	void operator+= (vex3f v);
	void operator-= (vex3f v);
	void operator*= (vex3f v);
	void operator/= (vex3f v);
	void operator+= (float v) { x += v; y += v; z += v; };
	void operator-= (float v) { x -= v; y -= v; z -= v; };
	void operator*= (float v) { x *= v; y *= v; z *= v; };
	void operator/= (float v) { x /= v; y /= v; z /= v; };
	void operator++ () { x += 1.0f; y += 1.0f; };
	void operator-- () { x -= 1.0f; y -= 1.0f; };

	bool operator== (vex3f v);
	bool operator== (float v);
	bool operator!= (vex3f v);
	bool operator!= (float v);
	bool operator< (vex3f v);
	bool operator< (float v);
	bool operator<= (vex3f v);
	bool operator<= (float v);
	bool operator> (vex3f v);
	bool operator> (float v);
	bool operator>= (vex3f v);
	bool operator>= (float v);

	void normalize();
	void ceil_();
	void floor_();
	void abs_();
	void sqrt_();
	void percent_(float v);
	void pow_(int v);
	void rand_(int v2, int v3);
	void atan2_(vex3f v);
	void atan_();
	void asin_();
	void acos_();
	void tan_();
	void sin_();
	void cos_();
	void average_();
	void log_();
	void round_();
	void trunc_();
	void exp_();
	void cbrt_();

	vex3f ceil();
	vex3f floor();
	vex3f abs();
	vex3f sqrt();
	vex3f percent(float v);
	vex3f pow(int v);
	vex3f rand(int v2, int v3);
	vex3f atan2(vex3f v);
	vex3f atan();
	vex3f asin();
	vex3f acos();
	vex3f tan();
	vex3f sin();
	vex3f cos();
	vex3f average();
	vex3f log();
	vex3f round();
	vex3f trunc();
	vex3f exp();
	vex3f cbrt();

	bool isEmpty();
};
// ////////////////////// //
struct vex3d {
	double x, y, z;
	vex3d();
	vex3d(double v1, double v2, double v3);
	vex3d(double v1, double v2);
	vex3d(double v1);
	vex3d(bool& v1, bool& v2, bool& v3) { x = std::atof(v1); y = std::atof(v2); z = std::atof(v3); };
	vex3d(bool& v1, bool& v2) { x = std::atof(v1); y = std::atof(v2); };
	vex3d(bool& v1) { x = std::atof(v1); y = std::atof(v1); z = std::atof(v1); };
	vex3d(std::string v1, std::string v2, std::string v3) { x = std::atof(v1.c_str()); y = std::atof(v2.c_str()); z = std::atof(v3.c_str()); };
	vex3d(std::string v1, std::string v2) { x = std::atof(v1.c_str()); y = std::atof(v2.c_str()); };
	vex3d(std::string v1) { x = std::atof(v1.c_str()); y = std::atof(v1.c_str()); z = std::atoi(v1.c_str()); };
	vex3d(vex2d v);
	vex3d(vex2i v);
	vex3d(vex2f v);
	vex3d(vex3f v);
	vex3d(vex3i v);
	vex3d(vex4f v);
	vex3d(vex4d v);
	vex3d(vex4i v);

	vex3d(vex2f v, float v1);
	vex3d(float v1, vex2f v);
	vex3d(vex2d v, float v1);
	vex3d(float v1, vex2d v);
	vex3d(vex2i v, float v1);
	vex3d(float v1, vex2i v);

	vex3d(vex2f v, double v1);
	vex3d(double v1, vex2f v);
	vex3d(vex2d v, double v1);
	vex3d(double v1, vex2d v);
	vex3d(vex2i v, double v1);
	vex3d(double v1, vex2i v);

	vex3d(vex2f v, int v1);
	vex3d(int v1, vex2f v);
	vex3d(vex2d v, int v1);
	vex3d(int v1, vex2d v);
	vex3d(vex2i v, int v1);
	vex3d(int v1, vex2i v);

	void operator= (vex2d v);
	void operator= (vex2i v);
	void operator= (vex2f v);
	void operator= (vex3f v);
	void operator= (vex3i v);
	void operator= (vex4f v);
	void operator= (vex4d v);
	void operator= (vex4i v);

	vex3d operator+ (vex4f v);
	vex3d operator- (vex4f v);
	vex3d operator* (vex4f v);
	vex3d operator/ (vex4f v);
	vex3d operator+ (vex4d v);
	vex3d operator- (vex4d v);
	vex3d operator* (vex4d v);
	vex3d operator/ (vex4d v);
	vex3d operator+ (vex4i v);
	vex3d operator- (vex4i v);
	vex3d operator* (vex4i v);
	vex3d operator/ (vex4i v);
	vex3d operator+ (vex3i v);
	vex3d operator- (vex3i v);
	vex3d operator* (vex3i v);
	vex3d operator/ (vex3i v);
	vex3d operator+ (vex3f v);
	vex3d operator- (vex3f v);
	vex3d operator* (vex3f v);
	vex3d operator/ (vex3f v);
	vex3d operator+ (vex2f v);
	vex3d operator- (vex2f v);
	vex3d operator* (vex2f v);
	vex3d operator/ (vex2f v);
	vex3d operator+ (vex2i v);
	vex3d operator- (vex2i v);
	vex3d operator* (vex2i v);
	vex3d operator/ (vex2i v);
	vex3d operator+ (vex2d v);
	vex3d operator- (vex2d v);
	vex3d operator* (vex2d v);
	vex3d operator/ (vex2d v);
	vex3d operator+ (vex3d v);
	vex3d operator- (vex3d v);
	vex3d operator* (vex3d v);
	vex3d operator/ (vex3d v);

	vex3d operator+ (double v);
	vex3d operator- (double v);
	vex3d operator* (double v);
	vex3d operator/ (double v);
	void operator= (double v);

	void operator+= (vex4d v);
	void operator-= (vex4d v);
	void operator*= (vex4d v);
	void operator/= (vex4d v);
	void operator+= (vex4i v);
	void operator-= (vex4i v);
	void operator*= (vex4i v);
	void operator/= (vex4i v);
	void operator+= (vex4f v);
	void operator-= (vex4f v);
	void operator*= (vex4f v);
	void operator/= (vex4f v);
	void operator+= (vex3i v);
	void operator-= (vex3i v);
	void operator*= (vex3i v);
	void operator/= (vex3i v);
	void operator+= (vex3f v);
	void operator-= (vex3f v);
	void operator*= (vex3f v);
	void operator/= (vex3f v);
	void operator+= (vex2f v);
	void operator-= (vex2f v);
	void operator*= (vex2f v);
	void operator/= (vex2f v);
	void operator+= (vex2i v);
	void operator-= (vex2i v);
	void operator*= (vex2i v);
	void operator/= (vex2i v);
	void operator+= (vex2d v);
	void operator-= (vex2d v);
	void operator*= (vex2d v);
	void operator/= (vex2d v);
	
	void operator+= (vex3d v);
	void operator-= (vex3d v);
	void operator*= (vex3d v);
	void operator/= (vex3d v);
	void operator+= (double v) { x += v; y += v; z += v; };
	void operator-= (double v) { x -= v; y -= v; z -= v; };
	void operator*= (double v) { x *= v; y *= v; z *= v; };
	void operator/= (double v) { x /= v; y /= v; z /= v; };
	void operator++ () { x += 1.0; y += 1.0; };
	void operator-- () { x -= 1.0; y -= 1.0; };

	bool operator== (vex3d v);
	bool operator== (double v);
	bool operator!= (vex3d v);
	bool operator!= (double v);
	bool operator< (vex3d v);
	bool operator< (double v);
	bool operator<= (vex3d v);
	bool operator<= (double v);
	bool operator> (vex3d  v);
	bool operator> (double v);
	bool operator>= (vex3d v);
	bool operator>= (double v);

	void normalize();
	void ceil_();
	void floor_();
	void abs_();
	void sqrt_();
	void percent_(float v);
	void pow_(int v);
	void rand_(int v2, int v3);
	void atan2_(vex3d v);
	void atan_();
	void asin_();
	void acos_();
	void tan_();
	void sin_();
	void cos_();
	void average_();
	void log_();
	void round_();
	void trunc_();
	void exp_();
	void cbrt_();

	vex3d ceil();
	vex3d floor();
	vex3d abs();
	vex3d sqrt();
	vex3d percent(float v);
	vex3d pow(int v);
	vex3d rand(int v2, int v3);
	vex3d atan2(vex3d v);
	vex3d atan();
	vex3d asin();
	vex3d acos();
	vex3d tan();
	vex3d sin();
	vex3d cos();
	vex3d average();
	vex3d log();
	vex3d round();
	vex3d trunc();
	vex3d exp();
	vex3d cbrt();

	bool isEmpty();
};
// ////////////////////// //
struct vex3b {
	bool x, y, z;
	vex3b();
	vex3b(bool v1, bool v2, bool v3);
	vex3b(bool v1, bool v2);
	vex3b(bool v1);
	void operator= (const bool v);
};
vex3b::vex3b() {
	x = y = z = 0;
};
vex3b::vex3b(bool v1, bool v2, bool v3) {
	this->x = v1;
	this->y = v2;
	this->z = v3;
};
vex3b::vex3b(bool v1, bool v2) {
	this->x = v1;
	this->y = v2;
	this->z = 0;
};
vex3b::vex3b(bool v1) {
	this->x = v1;
	this->y = v1;
	this->z = v1;
};
void vex3b::operator=(const bool v) {
	this->x = v;
	this->y = v;
	this->z = v;
};
// ////////////////////// //
struct vex3i {
	int x, y, z;
	vex3i();
	vex3i(int v1, int v2, int v3);
	vex3i(int v1, int v2);
	vex3i(int v1);
	vex3i(bool& v1, bool& v2, bool& v3) { x = std::atoi(v1); y = std::atoi(v2); z = std::atoi(v3); };
	vex3i(bool& v1, bool& v2) { x = std::atoi(v1); y = std::atoi(v2); };
	vex3i(bool& v1) { x = std::atoi(v1); y = std::atoi(v1); z = std::atoi(v1); };
	vex3i(std::string v1, std::string v2, std::string v3) { x = std::atoi(v1.c_str()); y = std::atoi(v2.c_str()); z = std::atoi(v3.c_str()); };
	vex3i(std::string v1, std::string v2) { x = std::atoi(v1.c_str()); y = std::atoi(v2.c_str()); };
	vex3i(std::string v1) { x = std::atoi(v1.c_str()); y = std::atoi(v1.c_str()); z = std::atoi(v1.c_str()); };
	vex3i(vex2d v);
	vex3i(vex2i v);
	vex3i(vex2f v);
	vex3i(vex3d v);
	vex3i(vex3f v);
	vex3i(vex4f v);
	vex3i(vex4d v);
	vex3i(vex4i v);

	vex3i(vex2f v, float v1);
	vex3i(float v1, vex2f v);
	vex3i(vex2d v, float v1);
	vex3i(float v1, vex2d v);
	vex3i(vex2i v, float v1);
	vex3i(float v1, vex2i v);

	vex3i(vex2f v, double v1);
	vex3i(double v1, vex2f v);
	vex3i(vex2d v, double v1);
	vex3i(double v1, vex2d v);
	vex3i(vex2i v, double v1);
	vex3i(double v1, vex2i v);

	vex3i(vex2f v, int v1);
	vex3i(int v1, vex2f v);
	vex3i(vex2d v, int v1);
	vex3i(int v1, vex2d v);
	vex3i(vex2i v, int v1);
	vex3i(int v1, vex2i v);

	void operator= (vex2d v);
	void operator= (vex2i v);
	void operator= (vex2f v);
	void operator= (vex3d v);
	void operator= (vex3f v);
	void operator= (vex4f v);
	void operator= (vex4d v);
	void operator= (vex4i v);

	vex3i operator+ (vex4f v);
	vex3i operator- (vex4f v);
	vex3i operator* (vex4f v);
	vex3i operator/ (vex4f v);
	vex3i operator+ (vex4d v);
	vex3i operator- (vex4d v);
	vex3i operator* (vex4d v);
	vex3i operator/ (vex4d v);
	vex3i operator+ (vex4i v);
	vex3i operator- (vex4i v);
	vex3i operator* (vex4i v);
	vex3i operator/ (vex4i v);
	vex3i operator+ (vex3f v);
	vex3i operator- (vex3f v);
	vex3i operator* (vex3f v);
	vex3i operator/ (vex3f v);
	vex3i operator+ (vex3d v);
	vex3i operator- (vex3d v);
	vex3i operator* (vex3d v);
	vex3i operator/ (vex3d v);
	vex3i operator+ (vex2f v);
	vex3i operator- (vex2f v);
	vex3i operator* (vex2f v);
	vex3i operator/ (vex2f v);
	vex3i operator+ (vex2i v);
	vex3i operator- (vex2i v);
	vex3i operator* (vex2i v);
	vex3i operator/ (vex2i v);
	vex3i operator+ (vex2d v);
	vex3i operator- (vex2d v);
	vex3i operator* (vex2d v);
	vex3i operator/ (vex2d v);
	vex3i operator+ (vex3i v);
	vex3i operator- (vex3i v);
	vex3i operator* (vex3i v);
	vex3i operator/ (vex3i v);

	vex3i operator+ (int v);
	vex3i operator- (int v);
	vex3i operator* (int v);
	vex3i operator/ (int v);
	void operator= (int v);

	void operator+= (vex4d v);
	void operator-= (vex4d v);
	void operator*= (vex4d v);
	void operator/= (vex4d v);
	void operator+= (vex4i v);
	void operator-= (vex4i v);
	void operator*= (vex4i v);
	void operator/= (vex4i v);
	void operator+= (vex4f v);
	void operator-= (vex4f v);
	void operator*= (vex4f v);
	void operator/= (vex4f v);
	void operator+= (vex3f v);
	void operator-= (vex3f v);
	void operator*= (vex3f v);
	void operator/= (vex3f v);
	void operator+= (vex3d v);
	void operator-= (vex3d v);
	void operator*= (vex3d v);
	void operator/= (vex3d v);
	void operator+= (vex2f v);
	void operator-= (vex2f v);
	void operator*= (vex2f v);
	void operator/= (vex2f v);
	void operator+= (vex2i v);
	void operator-= (vex2i v);
	void operator*= (vex2i v);
	void operator/= (vex2i v);
	void operator+= (vex2d v);
	void operator-= (vex2d v);
	void operator*= (vex2d v);
	void operator/= (vex2d v);

	void operator+= (vex3i v);
	void operator-= (vex3i v);
	void operator*= (vex3i v);
	void operator/= (vex3i v);
	void operator+= (int v) { x += v; y += v; z += v; };
	void operator-= (int v) { x -= v; y -= v; z -= v; };
	void operator*= (int v) { x *= v; y *= v; z *= v; };
	void operator/= (int v) { x /= v; y /= v; z /= v; };
	void operator++ () { x ++; y ++; };
	void operator-- () { x --; y --; };

	bool operator== (vex3i v);
	bool operator== (int v);
	bool operator!= (vex3i v);
	bool operator!= (int v);
	bool operator< (vex3i v);
	bool operator< (int v);
	bool operator<= (vex3i v);
	bool operator<= (int v);
	bool operator> (vex3i v);
	bool operator> (int v);
	bool operator>= (vex3i v);
	bool operator>= (int v);
	void log_();
	void exp_();
	void cbrt_();

	void normalize();
	void abs_();
	void sqrt_();
	void percent_(int v);
	void pow_(int v);
	void rand_(int v2, int v3);
	void atan2_(vex3i v);
	void atan_();
	void asin_();
	void acos_();
	void tan_();
	void sin_();
	void cos_();
	void average_();

	vex3i abs();
	vex3i sqrt();
	vex3i percent(int v);
	vex3i pow(int v);
	vex3i rand(int v2, int v3);
	vex3i atan2(vex3i v);
	vex3i atan();
	vex3i asin();
	vex3i acos();
	vex3i tan();
	vex3i sin();
	vex3i cos();
	vex3i average();
	vex3i log();
	vex3i exp();
	vex3i cbrt();

	bool isEmpty();
};
// /////////////////////////////////// ///
struct vex3s {
	std::string x, y, z;
	vex3s();
	vex3s(std::string v1, std::string v2, std::string v3);
	vex3s operator+ (const vex3s& v);

	vex3s operator+ (const std::string v);
	void operator= (const std::string v);
void operator+= (const vex3s& v);
};
vex3s::vex3s() {
	x = y = z = "";
};
vex3s::vex3s(std::string v1, std::string v2, std::string v3) {
	this->x = v1;
	this->y = v2;
	this->z = v3;
};
void vex3s::operator=(const std::string v) {
	this->x = v;
	this->y = v;
	this->z = v;
};
vex3s vex3s::operator+(const vex3s& v) {
	vex3s __temp;
	__temp.x = this->x + v.x;
	__temp.y = this->y + v.y;
	__temp.z = this->z + v.z;
	return __temp;
};
vex3s vex3s::operator+(const std::string v) {
	vex3s __temp;
	__temp.x = this->x + v;
	__temp.y = this->y + v;
	__temp.z = this->z + v;
	return __temp;
};
void vex3s::operator+=(const vex3s& v) {
	this->x += v.x;
	this->y += v.y;
	this->z += v.z;
};