void XsSolidCube(vex3f __scale) {
	glBegin(GL_QUADS);
	glNormal3f(1, 0, 0);
	glVertex3f(1 * __scale.x, -1 * __scale.y, 1 * __scale.z);
	glNormal3f(1, 0, 0);
	glVertex3f(1 * __scale.x, 1 * __scale.y, -1 * __scale.z);
	glNormal3f(1, 0, 0);
	glVertex3f(1 * __scale.x, 1 * __scale.y, 1 * __scale.z);
	glNormal3f(0, 0, -1);
	glVertex3f(1 * __scale.x, -1 * __scale.y, -1 * __scale.z);
	glNormal3f(0, 0, -1);
	glVertex3f(-1 * __scale.x, 1 * __scale.y, -1 * __scale.z);
	glNormal3f(0, 0, -1);
	glVertex3f(1 * __scale.x, 1 * __scale.y, -1 * __scale.z);
	glNormal3f(-1, 0, 0);
	glVertex3f(-1 * __scale.x, -1 * __scale.y, -1 * __scale.z);
	glNormal3f(-1, 0, 0);
	glVertex3f(-1 * __scale.x, 1 * __scale.y, 1 * __scale.z);
	glNormal3f(-1, 0, 0);
	glVertex3f(-1 * __scale.x, 1 * __scale.y, -1 * __scale.z);
	glNormal3f(0, -0, 1);
	glVertex3f(-1 * __scale.x, -1 * __scale.y, 1 * __scale.z);
	glNormal3f(0, -0, 1);
	glVertex3f(1 * __scale.x, 1 * __scale.y, 1 * __scale.z);
	glNormal3f(0, -0, 1);
	glVertex3f(-1 * __scale.x, 1 * __scale.y, 1 * __scale.z);
	glNormal3f(0, 1, 0);
	glVertex3f(-1 * __scale.x, 1 * __scale.y, -1 * __scale.z);
	glNormal3f(0, 1, 0);
	glVertex3f(1 * __scale.x, 1 * __scale.y, 1 * __scale.z);
	glNormal3f(0, 1, 0);
	glVertex3f(1 * __scale.x, 1 * __scale.y, -1 * __scale.z);
	glNormal3f(0, -1, -0);
	glVertex3f(1 * __scale.x, -1 * __scale.y, -1 * __scale.z);
	glNormal3f(0, -1, -0);
	glVertex3f(-1 * __scale.x, -1 * __scale.y, 1 * __scale.z);
	glNormal3f(0, -1, -0);
	glVertex3f(-1 * __scale.x, -1 * __scale.y, -1 * __scale.z);
	glNormal3f(1, 0, 0);
	glVertex3f(1 * __scale.x, -1 * __scale.y, 1 * __scale.z);
	glNormal3f(1, 0, 0);
	glVertex3f(1 * __scale.x, -1 * __scale.y, -1 * __scale.z);
	glNormal3f(1, 0, 0);
	glVertex3f(1 * __scale.x, 1 * __scale.y, -1 * __scale.z);
	glNormal3f(0, 0, -1);
	glVertex3f(1 * __scale.x, -1 * __scale.y, -1 * __scale.z);
	glNormal3f(0, 0, -1);
	glVertex3f(-1 * __scale.x, -1 * __scale.y, -1 * __scale.z);
	glNormal3f(0, 0, -1);
	glVertex3f(-1 * __scale.x, 1 * __scale.y, -1 * __scale.z);
	glNormal3f(-1, 0, 0);
	glVertex3f(-1 * __scale.x, -1 * __scale.y, -1 * __scale.z);
	glNormal3f(-1, 0, 0);
	glVertex3f(-1 * __scale.x, -1 * __scale.y, 1 * __scale.z);
	glNormal3f(-1, 0, 0);
	glVertex3f(-1 * __scale.x, 1 * __scale.y, 1 * __scale.z);
	glNormal3f(0, -0, 1);
	glVertex3f(-1 * __scale.x, -1 * __scale.y, 1 * __scale.z);
	glNormal3f(0, -0, 1);
	glVertex3f(1 * __scale.x, -1 * __scale.y, 1 * __scale.z);
	glNormal3f(0, -0, 1);
	glVertex3f(1 * __scale.x, 1 * __scale.y, 1 * __scale.z);
	glNormal3f(0, 1, 0);
	glVertex3f(-1 * __scale.x, 1 * __scale.y, -1 * __scale.z);
	glNormal3f(0, 1, 0);
	glVertex3f(-1 * __scale.x, 1 * __scale.y, 1 * __scale.z);
	glNormal3f(0, 1, 0);
	glVertex3f(1 * __scale.x, 1 * __scale.y, 1 * __scale.z);
	glNormal3f(0, -1, -0);
	glVertex3f(1 * __scale.x, -1 * __scale.y, -1 * __scale.z);
	glNormal3f(0, -1, -0);
	glVertex3f(1 * __scale.x, -1 * __scale.y, 1 * __scale.z);
	glNormal3f(0, -1, -0);
	glVertex3f(-1 * __scale.x, -1 * __scale.y, 1 * __scale.z);
	glEnd();
}